// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eEnDU8fhJg91JLNKsfGcFr
// Component: 92bllN-FoOAL
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: vsBMPoBaWTY/component
import Button from "../../Button"; // plasmic-import: lLYWjqtwRPx/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: eEnDU8fhJg91JLNKsfGcFr/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 92bllN-FoOAL/css

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

export const defaultHomepage__Args = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultHomepage__Args, props.args);
  const $props = args;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__x5FPp)}>
            <div className={classNames(projectcss.all, sty.freeBox___6Undr)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__eyB4N
                )}
              >
                {"Blockchain Explorer"}
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__gl2Ul)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2D0FO
                  )}
                >
                  {"Tokens"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Ibv
                  )}
                >
                  {"Resources"}
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__jzza3)}>
              <div className={classNames(projectcss.all, sty.freeBox__vk9EK)}>
                <TextInput
                  data-plasmic-name={"textInput"}
                  data-plasmic-override={overrides.textInput}
                  className={classNames("__wab_instance", sty.textInput)}
                  placeholder={
                    "Search by Address / Txn Hash /Block / Token /Ens"
                  }
                />

                <Button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yaMoe
                    )}
                  >
                    {"Button"}
                  </div>
                </Button>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__zwpGd)}>
              <div className={classNames(projectcss.all, sty.freeBox___4FRtW)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___9BrY9)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__wy0C4)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fwf1T)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sxTkr
                        )}
                      >
                        {"ETHEREUM TRANSACTION HISTORY IN 14 DAYS"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__pc7JB
                        )}
                      />
                    </div>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__mYvBy)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dIIkY)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lDf9O)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__niAgd
                        )}
                      >
                        {"ETHER PRICE"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___23Upw
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iTKkj
                        )}
                      >
                        {"@ 0.06529 BTC (-2.76%)"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5RBp1
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wzar6
                        )}
                      >
                        {"MARKET CAP"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9MwVu
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iRn2
                        )}
                      >
                        {""}
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___9B6Is)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___80UcZ
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fmJBy
                        )}
                      >
                        {"TRANSACTIONS"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___36FpR
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iowhk
                        )}
                      >
                        {"MED GAS PRICE\n36 Gwei ($1.47)"}
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__je5B4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hxfTi
                        )}
                      >
                        {"TRANSACTIONS"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__y6X9B
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__spMsn
                        )}
                      >
                        {"HASH RATE\n1,087,782.78 GH/s"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__tXn1B)}>
                <div className={classNames(projectcss.all, sty.freeBox__yqKba)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xbxAh
                    )}
                  >
                    {"Latest Blocks"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__xwk1B)}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.freeBox__iaAhB)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lVwdz
                    )}
                  >
                    {"Latest Transactions"}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ovVyy)}
                  />
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__jY6Yj)} />
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "textInput", "textbox", "button"],
  textInput: ["textInput", "textbox"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textInput: makeNodeComponent("textInput"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
